#!/usr/bin/env bash

/home/hx/.config/bspwm/autostart.sh &
/home/hx/.config/polybar/launch.sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V
bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap           6

bspc config normal_border_color "#3f4e4f"
bspc config focused_border_color "#aac4ff"
bspc config presel_feedback_color "#6272a4"

bspc config split_ratio          0.55
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a "TelegramDesktop" state=floating
