theme = "tokyonight"

[editor]
line-number = "relative"
true-color = true
mouse = false
cursorline = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.auto-save.after-delay]
enable = true
timeout = 5000
