if !has('gui_running') && &term =~ '^\%(screen\|tmux\)'
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif

call plug#begin('~/.vim/plugged')

Plug 'sheerun/vim-polyglot'
Plug 'vim-python/python-syntax'
Plug 'preservim/nerdtree'
Plug 'neoclide/coc.nvim', {'branch': 'release'}
Plug 'ryanoasis/vim-devicons'
Plug 'terryma/vim-multiple-cursors'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'jiangmiao/auto-pairs'
Plug 'tpope/vim-fugitive'
Plug 'ghifarit53/tokyonight-vim'

call plug#end()

set clipboard=unnamedplus
set number
set relativenumber
set autoindent
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set nobackup
set smarttab
set scrolloff=4
set nowrap
set incsearch
set mouse=a
set ignorecase
set termguicolors
set showmatch
set hlsearch
set encoding=UTF-8
set wildmenu
set wildmode=list:full
set nocompatible
set completeopt-=preview
set cursorline
let g:solarized_termcolors=256

syntax on
filetype on
filetype plugin indent on
set background=dark
let g:tokyonight_style = 'night' " available: night, storm
let g:tokyonight_enable_italic = 1
colorscheme tokyonight

let mapleader = " "

nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l
noremap <C-e> :NERDTreeToggle<CR>
noremap <S-m> :bdelete<CR>
noremap <S-h> :bprevious<CR>
noremap <S-l> :bnext<CR>
noremap <S-j> :<CR>
noremap <S-k> :<CR>
noremap <leader>e :NERDTreeToggle<CR>
noremap <leader>f :Files<CR>
noremap <leader>b :Buffers<CR>
noremap <leader>c :Colors<CR>
noremap <leader>h :History<CR>
noremap <leader>t :terminal<CR>

inoremap <expr> <Tab> coc#pum#visible() ? coc#pum#next(1) : "\<Tab>"
inoremap <expr> <S-Tab> coc#pum#visible() ? coc#pum#prev(1) : "\<S-Tab>"
inoremap <expr> <Return> coc#pum#visible() ? coc#pum#confirm() : "\<CR>"

" Python
let python_highlight_all = 1

" Status
" Clear status line when vimrc is reloaded.
set statusline=

" Status line left side.
set statusline+=\ %F\ %M\ %Y\ %R

" Use a divider to separate the left side from the right side.
set statusline+=%=

" Status line right side.
"set statusline+=\ ascii:\ %b\ hex:\ 0x%B\ row:\ %l\ col:\ %c\ percent:\ %p%%
set statusline+=\ row:\ %l\ col:\ %c\ percent:\ %p%%

" Show the status on the second to last line.
set laststatus=2

