if !has('gui_running') && &term =~ '^\%(screen\|tmux\)'
  let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
  let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif

syntax on
filetype on
filetype plugin indent on
set background=dark
colorscheme onedark
let g:onedark_terminal_italics=1
let g:onedark_termcolors=256
"let ayucolor="migrate"

set number
set relativenumber
set autoindent
set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set nobackup
set smarttab
set scrolloff=18
set nowrap
set incsearch
set mouse=a
set ignorecase
set termguicolors
set showmatch
set hlsearch
set encoding=UTF-8
set wildmenu
set wildmode=list:full
set nocompatible
set completeopt-=preview " For No Previews
set cursorline
let g:solarized_termcolors=256

call plug#begin()

Plug 'ericbn/vim-solarized'
Plug 'sheerun/vim-polyglot'
Plug 'vim-python/python-syntax'
Plug 'https://github.com/preservim/nerdtree' " NerdTree
Plug 'https://github.com/neoclide/coc.nvim'  " Auto Completion
Plug 'https://github.com/ryanoasis/vim-devicons' " Developer Icons
Plug 'https://github.com/tc50cal/vim-terminal' " Vim Terminal
Plug 'https://github.com/terryma/vim-multiple-cursors' " CTRL + N for multiple cursors
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
Plug 'jiangmiao/auto-pairs'
Plug 'tpope/vim-fugitive'
Plug 'ayu-theme/ayu-vim'
Plug 'joshdick/onedark.vim'

call plug#end()

let mapleader = " "
"set timeoutlen 500

"noremap <C-f> :NERDTreeFocus<CR>
"noremap <C-n> :NERDTree<CR>
noremap <C-e> :NERDTreeToggle<CR>
noremap <S-m> :bdelete<CR>
noremap <S-h> :bprevious<CR>
noremap <S-l> :bnext<CR>
noremap <S-j> :<CR>
"noremap <g-d> :call CocActionAsync('jumpDefinition')<CR>
noremap <leader>e :NERDTreeToggle<CR>
noremap <leader>f :Files<CR>
noremap <leader>b :Buffers<CR>
noremap <leader>c :Colors<CR>
noremap <leader>h :History<CR>
noremap <leader>t :terminal<CR>

inoremap <expr> <Tab> coc#pum#visible() ? coc#pum#next(1) : "\<Tab>"
inoremap <expr> <S-Tab> coc#pum#visible() ? coc#pum#prev(1) : "\<S-Tab>"
inoremap <expr> <Return> coc#pum#visible() ? coc#pum#confirm() : "\<CR>"

" Python
let python_highlight_all = 1

" Status
" Clear status line when vimrc is reloaded.
set statusline=

" Status line left side.
set statusline+=\ %F\ %M\ %Y\ %R

" Use a divider to separate the left side from the right side.
set statusline+=%=

" Status line right side.
"set statusline+=\ ascii:\ %b\ hex:\ 0x%B\ row:\ %l\ col:\ %c\ percent:\ %p%%
set statusline+=\ row:\ %l\ col:\ %c\ percent:\ %p%%

" Show the status on the second to last line.
set laststatus=2
