return {
    -- "hrsh7th/nvim-cmp",
    -- version = false,
    -- event = "InsertEnter",
    -- dependencies = {
    --     "hrsh7th/cmp-buffer",
    --     "hrsh7th/cmp-path",
    --     "hrsh7th/cmp-nvim-lsp",
    --     "saadparwaiz1/cmp_luasnip",
    --     {
    --         "L3MON4D3/LuaSnip",
    --         -- Replace <CurrentMajor> by the latest released major (first number of latest release)
    --         version = "2.*",
    --     },
    -- },
    -- config = function ()
    --     -- luasnip setup
    --     local luasnip = require("luasnip")

    --     -- Icons
    --     local kind_icons = {
    --         Text = "",
    --         Method = "",
    --         Function = "󰊕",
    --         Constructor = "",
    --         Field = "",
    --         Variable = "󰫧",
    --         Class = "",
    --         Interface = "",
    --         Module = "",
    --         Property = "",
    --         Unit = "",
    --         Value = "",
    --         Enum = "",
    --         Keyword = "󰌆",
    --         Snippet = "",
    --         Color = "",
    --         File = "",
    --         Reference = "",
    --         Folder = "",
    --         EnumMember = "",
    --         Constant = "",
    --         Struct = "",
    --         Event = "",
    --         Operator = "",
    --         TypeParameter = ""
    --     }

    --     -- nvim-cmp setup
    --     local cmp = require 'cmp'
    --     cmp.setup {
    --         formatting = {
    --             format = function(entry, vim_item)
    --                 local lspkind_ok, lspkind = pcall(require, "lspkind")
    --                 if not lspkind_ok then
    --                     -- From kind_icons array
    --                     vim_item.kind = string.format('%s %s', kind_icons[vim_item.kind], vim_item.kind) -- This concatonates the icons with the name of the item kind
    --                     -- Source
    --                     vim_item.menu = ({
    --                         buffer = "[Buffer]",
    --                         nvim_lsp = "[LSP]",
    --                         luasnip = "[LuaSnip]",
    --                         nvim_lua = "[Lua]",
    --                     })[entry.source.name]
    --                     return vim_item
    --                 else
    --                     -- From lspkind
    --                     return lspkind.cmp_format()
    --                 end
    --             end
    --         },
    --         snippet = {
    --             expand = function(args)
    --                 luasnip.lsp_expand(args.body)
    --             end,
    --         },
    --         window = {
    --             completion = cmp.config.window.bordered(),
    --             documentation = cmp.config.window.bordered(),
    --         },
    --         mapping = cmp.mapping.preset.insert({
    --             ['<C-u>'] = cmp.mapping.scroll_docs(-4), -- Up
    --             ['<C-d>'] = cmp.mapping.scroll_docs(4), -- Down
    --             -- C-b (back) C-f (forward) for snippet placeholder navigation.
    --             ['<C-Space>'] = cmp.mapping.complete(),
    --             ['<CR>'] = cmp.mapping.confirm {
    --                 behavior = cmp.ConfirmBehavior.Replace,
    --                 select = true,
    --             },
    --             ['<Tab>'] = cmp.mapping(function(fallback)
    --                 if cmp.visible() then
    --                     cmp.select_next_item()
    --                 elseif luasnip.expand_or_jumpable() then
    --                     luasnip.expand_or_jump()
    --                 else
    --                     fallback()
    --                 end
    --             end, { 'i', 's' }),
    --             ['<S-Tab>'] = cmp.mapping(function(fallback)
    --                 if cmp.visible() then
    --                     cmp.select_prev_item()
    --                 elseif luasnip.jumpable(-1) then
    --                     luasnip.jump(-1)
    --                 else
    --                     fallback()
    --                 end
    --             end, { 'i', 's' }),
    --         }),
    --         sources = {
    --             { name = 'nvim_lsp' },
    --             { name = 'luasnip' },
    --             { name = 'buffer' },
    --             { name = 'path' },
    --         },
    --     }
    -- end
}
