#! /usr/bin/env bash

# Auto Start Section
killall volumeicon 

pulseaudio --start &
nitrogen --restore &
xrdb ~/.Xresources &
$HOME/.config/polybar/launch.sh &
nm-applet &
/run/current-system/sw/bin/emacs --daemon &
sleep 1; volumeicon &
flameshot &

# bspwm 
bspc monitor -d 1 2 3 4 5

bspc config border_width         2
bspc config window_gap           6

bspc config normal_border_color "#44475a"
bspc config focused_border_color "#bd93f9"
bspc config presel_feedback_color "#6272a4"

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a TelegramDesktop state=floating
bspc rule -a mpv state=floating
bspc rule -a Emacs state=tiled
bspc rule -a "VirtualBox Manager" state=floating
bspc rule -a "VirtualBox Machine" state=floating
bspc rule -a mpv state=floating
